/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discover the active API major version */
        get: operations["getApiVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List one authorized tenant's assets in stable ID order
         * @description The configured bearer identity must have a current metadata.read grant for the selected tenant. The route is absent without complete bearer configuration. A cursor traversal is not a cross-request snapshot.
         */
        get: operations["listAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiDescription: {
            /** @constant */
            service: "FleetIQ";
            /** @constant */
            version: "v1";
        };
        AssetTypeRef: {
            id: string;
            version: number;
        };
        AssetSummary: {
            id: string;
            tenant_id: string;
            name: string;
            asset_type: components["schemas"]["AssetTypeRef"];
        };
        AssetPage: {
            assets: components["schemas"]["AssetSummary"][];
            /** @description Exclusive cursor for the next page, or null when no next page exists. */
            next_after: string | null;
        };
        /** @description Minimum application/problem+json shape. Future compatible problems may include optional fields. */
        Problem: {
            type: string;
            title: string;
            status: number;
        };
    };
    responses: {
        /** @description Invalid tenant, limit, cursor, or query. */
        InvalidRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:fleetiq:problem:invalid-request",
                 *       "title": "Invalid request",
                 *       "status": 400
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A bearer credential was absent or rejected. */
        Unauthenticated: {
            headers: {
                "WWW-Authenticate"?: "Bearer realm=\"FleetIQ\"";
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:fleetiq:problem:unauthorized",
                 *       "title": "Authentication required",
                 *       "status": 401
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The actor has no current metadata.read grant for this tenant. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:fleetiq:problem:forbidden",
                 *       "title": "Access denied",
                 *       "status": 403
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A safe, bounded server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:fleetiq:problem:internal-error",
                 *       "title": "Internal server error",
                 *       "status": 500
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getApiVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active product API major version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "service": "FleetIQ",
                     *       "version": "v1"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiDescription"];
                };
            };
        };
    };
    listAssets: {
        parameters: {
            query?: {
                /** @description Maximum asset summaries returned. */
                limit?: number;
                /** @description Exclusive asset-ID cursor from a previous page. */
                after?: string;
            };
            header?: never;
            path: {
                /** @description The tenant selected for the current authorization check. */
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded asset summaries. An empty catalogue returns an empty array and a null cursor. */
            200: {
                headers: {
                    /** @description Protected responses are not stored by shared or browser caches. */
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "assets": [
                     *         {
                     *           "id": "asset-1",
                     *           "tenant_id": "tenant-a",
                     *           "name": "Primary machine",
                     *           "asset_type": {
                     *             "id": "generic.machine",
                     *             "version": 1
                     *           }
                     *         }
                     *       ],
                     *       "next_after": null
                     *     }
                     */
                    "application/json": components["schemas"]["AssetPage"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
}
